# params.yaml
index_col: 'id'
target_col: 'price'
one_hot_drop: 'if_binary'
n_splits: 5
shuffle: True
random_state: 42
metrics: ['r2', 'neg_mean_absolute_error', 'neg_root_mean_squared_error']
n_jobs: -1 
iterations: 1000
learning_rate: 0.05
depth: 8
verbose: 100
early_stopping_rounds: 50
handle_unknown: 'use_encoded_value'
unknown_value: -1
n_estimators: 100
retrain: True